### ISSUE TITLE
Bad state: No element

### ISSUE THREAD

**Issue by joshua750** [DevsOnFlutter/file_manager#26]
I am try to running ios  simulator getting this errror 

import 'dart:io';
import 'package:file_manager/file_manager.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:path_provider/path_provider.dart';

class Pdflist extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _PdflistState();
  }
}

class _PdflistState extends State<Pdflist> {

  @override
  void initState() {

    super.initState();

    permission();
  }

   Future<void> permission() async {
     await FileManager.requestFilesAccessPermission();
   }
  final FileManagerController controller = FileManagerController();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("PDF File list from Storage"),
        backgroundColor: Colors.redAccent,
      ),
      body: FileManager(
        controller: controller,
        builder: (context, snapshot) {
          final List<FileSystemEntity> entities = snapshot;
          return ListView.builder(
            itemCount: entities.length,
            itemBuilder: (context, index) {
              return Card(
                child: ListTile(
                  leading: FileManager.isFile(entities[index])
                      ? Icon(Icons.feed_outlined)
                      : Icon(Icons.folder),
                  title: Text(FileManager.basename(entities[index])),
                  onTap: () {
                    if (FileManager.isDirectory(entities[index])) {
                      controller.openDirectory(entities[index]);   // open directory
                    } else {
                      // Perform file-related tasks.
                    }
                  },
                ),
              );
            },
          );
        },
      ),
    );
  }
}

Launching lib/main.dart on iPhone 11 in debug mode...
Running Xcode build...
Xcode build done.                                           32.8s
[VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(35)] Using the Impeller rendering backend.
Debug service listening on ws://127.0.0.1:52812/3UHvPYDmDbM=/ws
Syncing files to device iPhone 11...
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: Only Android is supported
#0      FileManager.requestFilesAccessPermission (package:file_manager/file_manager.dart:121:7)
#1      _PdflistState.permission (package:documentviewer/pdflist/Pdflist.dart:26:24)
#2      _PdflistState.initState (package:documentviewer/pdflist/Pdflist.dart:22:5)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5219:55)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
#7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6435:14)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
#10     ComponentElement.performRebuild (pac<…>

======== Exception caught by widgets library =======================================================
The following StateError was thrown building FutureBuilder<List<Directory>?>(dirty, state: _FutureBuilderState<List<Directory>?>#75356):
Bad state: No element

The relevant error-causing widget was:

**Comment by Galti** [comment]
I had the same issue on iOS and solved it by setting the current path of the controller BEFORE the build method.
I change it in **initState**.

`@override`
 `void initState() {`
 `   super.initState();`

 `   controller.setCurrentPath = path;`
`}`
